package PO;
// default package
// Generated 2017-5-25 12:54:38 by Hibernate Tools 4.0.1.Final

/**
 * StockData generated by hbm2java
 */
public class StockData implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -5301952004185665092L;
	private StockDataId id;

	public StockData() {
	}

	public StockData(StockDataId id) {
		this.id = id;
	}

	public StockDataId getId() {
		return this.id;
	}

	public void setId(StockDataId id) {
		this.id = id;
	}

}
