package PO;
// default package
// Generated 2017-5-25 12:54:38 by Hibernate Tools 4.0.1.Final

/**
 * StockCurrentData generated by hbm2java
 */
public class StockCurrentData implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -7084717567992884535L;
	private StockCurrentDataId id;

	public StockCurrentData() {
	}

	public StockCurrentData(StockCurrentDataId id) {
		this.id = id;
	}

	public StockCurrentDataId getId() {
		return this.id;
	}

	public void setId(StockCurrentDataId id) {
		this.id = id;
	}

}
