package PO.user;
// Generated 2017-6-2 16:54:51 by Hibernate Tools 5.2.1.Final

/**
 * UserStockOwned generated by hbm2java
 */
public class UserStockOwned implements java.io.Serializable {

	private UserStockOwnedId id;
	private UserData userData;
	private Integer stocknum;

	public UserStockOwned() {
	}

	public UserStockOwned(UserStockOwnedId id, UserData userData) {
		this.id = id;
		this.userData = userData;
	}

	public UserStockOwned(UserStockOwnedId id, UserData userData, Integer stocknum) {
		this.id = id;
		this.userData = userData;
		this.stocknum = stocknum;
	}

	public UserStockOwnedId getId() {
		return this.id;
	}

	public void setId(UserStockOwnedId id) {
		this.id = id;
	}

	public UserData getUserData() {
		return this.userData;
	}

	public void setUserData(UserData userData) {
		this.userData = userData;
	}

	public Integer getStocknum() {
		return this.stocknum;
	}

	public void setStocknum(Integer stocknum) {
		this.stocknum = stocknum;
	}

}
