package PO.user;
// Generated 2017-6-2 16:54:51 by Hibernate Tools 5.2.1.Final

import java.util.HashSet;
import java.util.Set;

/**
 * UserData generated by hbm2java
 */
public class UserData implements java.io.Serializable {

	private String username;
	private String password;
	private byte[] avatar;
	private Set userStockOwneds = new HashSet(0);
	private UserAccount userAccount;

	public UserData() {
	}

	public UserData(String username, String password) {
		this.username = username;
		this.password = password;
	}

	public UserData(String username, String password, byte[] avatar, Set userStockOwneds, UserAccount userAccount) {
		this.username = username;
		this.password = password;
		this.avatar = avatar;
		this.userStockOwneds = userStockOwneds;
		this.userAccount = userAccount;
	}

	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public byte[] getAvatar() {
		return this.avatar;
	}

	public void setAvatar(byte[] avatar) {
		this.avatar = avatar;
	}

	public Set getUserStockOwneds() {
		return this.userStockOwneds;
	}

	public void setUserStockOwneds(Set userStockOwneds) {
		this.userStockOwneds = userStockOwneds;
	}

	public UserAccount getUserAccount() {
		return this.userAccount;
	}

	public void setUserAccount(UserAccount userAccount) {
		this.userAccount = userAccount;
	}

}
