package PO.user;
// Generated 2017-6-2 16:54:51 by Hibernate Tools 5.2.1.Final

import java.util.Date;

/**
 * UserAccount generated by hbm2java
 */
public class UserAccount implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -6197363525843231968L;
	private String username;
	//可交易金额
	private Double availablePrincipal;
	//已用于购买的金额
	private Double storagePrincipal;
	
	private Double profit;
	private Date signdate;
	
	private Integer consecutiveDaysNum;
	//仅用于计算profit ，不向上层展示
	private Double historyPrincipal;

	public UserAccount() {
	}

	
	public UserAccount( Double availablePrincipal, Double storagePrincipal, Double profit,
			Date signdate, Integer consecutiveDaysNum, Double historyPrincipal) {
		this.availablePrincipal = availablePrincipal;
		this.storagePrincipal = storagePrincipal;
		this.profit = profit;
		this.signdate = signdate;
		this.consecutiveDaysNum = consecutiveDaysNum;
		this.historyPrincipal = historyPrincipal;
	}

	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	
	public Double getAvailablePrincipal() {
		return this.availablePrincipal;
	}

	public void setAvailablePrincipal(Double availablePrincipal) {
		this.availablePrincipal = availablePrincipal;
	}

	public Double getStoragePrincipal() {
		return this.storagePrincipal;
	}

	public void setStoragePrincipal(Double storagePrincipal) {
		this.storagePrincipal = storagePrincipal;
	}

	public Double getProfit() {
		return this.profit;
	}

	public void setProfit(Double profit) {
		this.profit = profit;
	}

	public Date getSigndate() {
		return this.signdate;
	}

	public void setSigndate(Date signdate) {
		this.signdate = signdate;
	}

	public Integer getConsecutiveDaysNum() {
		return this.consecutiveDaysNum;
	}

	public void setConsecutiveDaysNum(Integer consecutiveDaysNum) {
		this.consecutiveDaysNum = consecutiveDaysNum;
	}

	public Double getHistoryPrincipal() {
		return this.historyPrincipal;
	}

	public void setHistoryPrincipal(Double historyPrincipal) {
		this.historyPrincipal = historyPrincipal;
	}

}
