package DAO;
// Generated 2017-5-17 9:58:01 by Hibernate Tools 5.2.1.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Grade generated by hbm2java
 */
public class Grade implements java.io.Serializable {

	private Integer gid;
	private String gname;
	private String gdesc;
	private Set<Student> students = new HashSet<Student>(0);

	public Grade() {
	}

	public Grade(String gname) {
		this.gname = gname;
	}

	public Grade(String gname, String gdesc, Set<Student> students) {
		this.gname = gname;
		this.gdesc = gdesc;
		this.students = students;
	}

	public Integer getGid() {
		return this.gid;
	}

	public void setGid(Integer gid) {
		this.gid = gid;
	}

	public String getGname() {
		return this.gname;
	}

	public void setGname(String gname) {
		this.gname = gname;
	}

	public String getGdesc() {
		return this.gdesc;
	}

	public void setGdesc(String gdesc) {
		this.gdesc = gdesc;
	}

	public Set<Student> getStudents() {
		return this.students;
	}

	public void setStudents(Set<Student> students) {
		this.students = students;
	}

}
